#!/usr/bin/env python3
"""Generate an Ed25519 signing keypair for firmware .sim signing.

Default output:
  ~/.nabaztag/signing_key.bin     32 bytes raw private seed (chmod 600)
  firmware-arm/keys/signing_pubkey.h     C header with the 32-byte pubkey

The private key NEVER touches the repo. The public key is embedded in
the firmware so the rabbit can verify .sim signatures before flashing.
"""

import argparse
import os
import secrets
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ed25519


def fmt_c_header(pubkey: bytes, var: str = "nab_signing_pubkey") -> str:
    rows = []
    for i in range(0, len(pubkey), 8):
        chunk = ", ".join(f"0x{b:02x}" for b in pubkey[i:i + 8])
        rows.append(f"    {chunk},")
    body = "\n".join(rows)
    return (
        "/* Generated by firmware-arm/signing/gen_key.py — do not edit. */\n"
        "#ifndef NAB_SIGNING_PUBKEY_H\n"
        "#define NAB_SIGNING_PUBKEY_H\n\n"
        "#include <stdint.h>\n\n"
        f"static const uint8_t {var}[32] = {{\n{body}\n}};\n\n"
        "#endif\n"
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--priv", default=str(Path.home() / ".nabaztag" / "signing_key.bin"),
        help="Where to write the private seed (32 raw bytes). Default: ~/.nabaztag/signing_key.bin",
    )
    p.add_argument(
        "--pub-header",
        default=str(Path(__file__).resolve().parent.parent / "keys" / "signing_pubkey.h"),
        help="Where to write the C header with the public key. Default: firmware-arm/keys/signing_pubkey.h",
    )
    p.add_argument(
        "--force", action="store_true",
        help="Overwrite the private key if it already exists. Default refuses (safety).",
    )
    args = p.parse_args()

    priv_path = Path(args.priv)
    pub_path = Path(args.pub_header)

    if priv_path.exists() and not args.force:
        print(f"refuse: {priv_path} already exists. Pass --force to replace it.", file=sys.stderr)
        return 2

    priv = secrets.token_bytes(32)
    pub = ed25519.secret_to_public(priv)

    priv_path.parent.mkdir(parents=True, exist_ok=True)
    pub_path.parent.mkdir(parents=True, exist_ok=True)

    # Write with strict perms
    fd = os.open(priv_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "wb") as fh:
        fh.write(priv)
    pub_path.write_text(fmt_c_header(pub), encoding="utf-8")

    print(f"wrote private seed → {priv_path} (chmod 600)")
    print(f"wrote public header → {pub_path}")
    print(f"pubkey (hex)        = {pub.hex()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
